"""
AI Operations Brain — Seed data for Project Management entities.
Provides realistic demo data for: Projects, Plants, Users, PTW, Procedures,
Managed Work Orders, Incident Reports, Quality Inspections, Action Items.
"""
from __future__ import annotations
from datetime import datetime

# ─────────────────────────────────────────────────────────────────────────────
# Users
# ─────────────────────────────────────────────────────────────────────────────
USERS = [
    {"id": "USR-001", "employee_id": "EMP-001", "name": "James Mitchell",
     "email": "j.mitchell@plant.com", "department": "Maintenance",
     "role": "technician", "certifications": ["CSWIP 3.1", "BOSIET"],
     "plant_ids": ["PLT-001", "PLT-002"], "is_active": True},
    {"id": "USR-002", "employee_id": "EMP-002", "name": "Sarah Chen",
     "email": "s.chen@plant.com", "department": "Maintenance",
     "role": "supervisor", "certifications": ["NEBOSH", "IOSH"],
     "plant_ids": ["PLT-001", "PLT-002", "PLT-003"], "is_active": True},
    {"id": "USR-003", "employee_id": "EMP-003", "name": "David Okonkwo",
     "email": "d.okonkwo@plant.com", "department": "HSE",
     "role": "safety_officer", "certifications": ["NEBOSH GC", "IEMA", "HAZOP Leader"],
     "plant_ids": ["PLT-001", "PLT-002", "PLT-003"], "is_active": True},
    {"id": "USR-004", "employee_id": "EMP-004", "name": "Maria Santos",
     "email": "m.santos@plant.com", "department": "Operations",
     "role": "area_authority", "certifications": ["NEBOSH", "Process Safety"],
     "plant_ids": ["PLT-001"], "is_active": True},
    {"id": "USR-005", "employee_id": "EMP-005", "name": "Robert Halliday",
     "email": "r.halliday@plant.com", "department": "Engineering",
     "role": "authorized_person", "certifications": ["NEBOSH Dip", "Electrical AP", "Mechanical AP"],
     "plant_ids": ["PLT-001", "PLT-002", "PLT-003"], "is_active": True},
    {"id": "USR-006", "employee_id": "EMP-006", "name": "Linda Park",
     "email": "l.park@plant.com", "department": "Engineering",
     "role": "manager", "certifications": ["PMP", "NEBOSH Dip", "CMgr"],
     "plant_ids": ["PLT-001", "PLT-002", "PLT-003"], "is_active": True},
    {"id": "USR-007", "employee_id": "EMP-007", "name": "Tom Fletcher",
     "email": "t.fletcher@plant.com", "department": "Quality",
     "role": "quality_inspector", "certifications": ["CSWIP 3.1", "ISO 9001 Lead Auditor"],
     "plant_ids": ["PLT-001", "PLT-002"], "is_active": True},
    {"id": "USR-008", "employee_id": "EMP-008", "name": "Ahmed Al-Rashid",
     "email": "a.alrashid@plant.com", "department": "Maintenance",
     "role": "technician", "certifications": ["Instrument Tech", "BOSIET"],
     "plant_ids": ["PLT-002", "PLT-003"], "is_active": True},
]

# ─────────────────────────────────────────────────────────────────────────────
# Projects
# ─────────────────────────────────────────────────────────────────────────────
PROJECTS = [
    {
        "id": "PRJ-001",
        "code": "REFINERY-ALPHA",
        "name": "Alpha Refinery Complex",
        "description": "Main crude oil processing facility — 120,000 bpd capacity",
        "type": "Industrial",
        "phase": "Operations",
        "status": "Active",
        "location": "Houston, TX",
        "plant_ids": ["PLT-001", "PLT-002"],
        "equipment_ids": ["P-101", "P-102", "HE-301", "V-201"],
        "manager_id": "USR-006",
        "start_date": "2018-01-01",
        "end_date": None,
        "tags": ["refinery", "crude", "tier-1"],
        "created_by": "USR-006",
        "created_at": datetime(2018, 1, 1, ),
        "updated_at": datetime(2026, 1, 1, ),
    },
    {
        "id": "PRJ-002",
        "code": "T&I-2026",
        "name": "2026 Turnaround & Inspection",
        "description": "Scheduled 5-year turnaround for CDU and hydrotreater units",
        "type": "Turnaround",
        "phase": "Planning",
        "status": "Active",
        "location": "Houston, TX",
        "plant_ids": ["PLT-001"],
        "equipment_ids": ["P-101", "HE-301", "V-201"],
        "manager_id": "USR-006",
        "start_date": "2026-09-01",
        "end_date": "2026-10-15",
        "tags": ["turnaround", "shutdown", "2026"],
        "created_by": "USR-006",
        "created_at": datetime(2026, 3, 1, ),
        "updated_at": datetime(2026, 6, 1, ),
    },
    {
        "id": "PRJ-003",
        "code": "UTIL-BETA",
        "name": "Beta Utilities Block",
        "description": "Steam generation, cooling water, and instrument air systems",
        "type": "Industrial",
        "phase": "Operations",
        "status": "Active",
        "location": "Houston, TX",
        "plant_ids": ["PLT-003"],
        "equipment_ids": [],
        "manager_id": "USR-006",
        "start_date": "2020-05-01",
        "end_date": None,
        "tags": ["utilities", "steam", "cooling-water"],
        "created_by": "USR-006",
        "created_at": datetime(2020, 5, 1, ),
        "updated_at": datetime(2026, 1, 1, ),
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Plants
# ─────────────────────────────────────────────────────────────────────────────
PLANTS = [
    {
        "id": "PLT-001",
        "code": "CDU-01",
        "name": "Crude Distillation Unit",
        "project_id": "PRJ-001",
        "type": "Process Unit",
        "location": "Block A, Row 3",
        "area": "North Plot",
        "description": "Primary atmospheric distillation column and associated equipment",
        "equipment_ids": ["P-101", "HE-301", "V-201"],
        "status": "Operational",
        "responsible_person_id": "USR-004",
        "created_at": datetime(2018, 1, 1, ),
    },
    {
        "id": "PLT-002",
        "code": "HDT-01",
        "name": "Naphtha Hydrotreater",
        "project_id": "PRJ-001",
        "type": "Process Unit",
        "location": "Block B, Row 1",
        "area": "South Plot",
        "description": "Catalytic hydrotreating unit for naphtha desulphurisation",
        "equipment_ids": ["P-102"],
        "status": "Operational",
        "responsible_person_id": "USR-004",
        "created_at": datetime(2018, 6, 1, ),
    },
    {
        "id": "PLT-003",
        "code": "UTL-01",
        "name": "Utilities – Steam & CW",
        "project_id": "PRJ-003",
        "type": "Utilities",
        "location": "Block C",
        "area": "East Plot",
        "description": "High-pressure steam generation (40 bar) and cooling water supply",
        "equipment_ids": [],
        "status": "Operational",
        "responsible_person_id": "USR-004",
        "created_at": datetime(2020, 5, 1, ),
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Permit to Work
# ─────────────────────────────────────────────────────────────────────────────
PERMITS = [
    {
        "id": "PTW-001",
        "permit_number": "PTW-2026-0001",
        "permit_type": "hot_work",
        "title": "Weld repair of P-101 suction flange",
        "scope_of_work": "Remove corroded flange gasket, clean weld face, and perform fillet weld repair on 6-inch suction line to P-101 pump casing. Post-weld heat treatment required.",
        "project_id": "PRJ-001",
        "plant_id": "PLT-001",
        "equipment_ids": ["P-101"],
        "location_description": "CDU Pump Bay A, Grid J-14",
        "area_classification": "Zone 1 – Ex d / Ex e",
        "planned_start": "2026-07-25T06:00:00",
        "planned_end": "2026-07-25T18:00:00",
        "status": "active",
        "hazards": [
            {"hazard": "Hydrocarbon vapours ignition", "likelihood": "Medium", "severity": "Critical", "mitigation": "Continuous gas monitoring, hot work barriers, fire watch"},
            {"hazard": "Hot surfaces / burns", "likelihood": "High", "severity": "Medium", "mitigation": "Insulated gloves, face shield, FR clothing"},
            {"hazard": "UV radiation from welding arc", "likelihood": "High", "severity": "Medium", "mitigation": "Welding screen, shade-10+ lens"},
        ],
        "ppe_requirements": [
            {"item": "Fire-resistant coverall", "specification": "EN ISO 11612 Level A1 B1 C1"},
            {"item": "Welding gloves", "specification": "EN 12477 Type A"},
            {"item": "Auto-darkening welding helmet", "specification": "EN 379 Shade 10"},
            {"item": "Safety boots", "specification": "EN ISO 20345 S3"},
        ],
        "isolation_points": [
            {"tag_number": "XV-1001A", "description": "P-101 suction isolation valve", "isolation_type": "closed_locked", "verified_by": "USR-004", "verified_at": "2026-07-25T05:45:00"},
            {"tag_number": "XV-1001B", "description": "P-101 discharge isolation valve", "isolation_type": "closed_locked", "verified_by": "USR-004", "verified_at": "2026-07-25T05:45:00"},
            {"tag_number": "ESD-1001", "description": "P-101 electrical isolation (MCC-A, CB-12)", "isolation_type": "LOTO", "verified_by": "USR-005", "verified_at": "2026-07-25T05:50:00"},
        ],
        "gas_tests": [
            {"tested_by": "David Okonkwo", "test_time": "2026-07-25T05:55:00", "gas": "Hydrocarbon (LEL)", "result": "pass", "ppm": None, "lel_percent": 0.0},
            {"tested_by": "David Okonkwo", "test_time": "2026-07-25T05:55:00", "gas": "H2S", "result": "pass", "ppm": 0.2, "lel_percent": None},
        ],
        "simops_conflicts": [],
        "emergency_response_ref": "ERP-CDU-001",
        "work_order_id": "MWO-001",
        "originator_id": "USR-001",
        "originator_name": "James Mitchell",
        "originator_date": "2026-07-23T09:00:00",
        "originator_comments": "Flange leaking — immediate repair required before shutdown deadline",
        "area_authority_id": "USR-004",
        "area_authority_name": "Maria Santos",
        "area_authority_decision": "approved",
        "area_authority_comments": "Equipment deenergised and drained. Scope confirmed.",
        "area_authority_date": "2026-07-23T14:00:00",
        "safety_officer_id": "USR-003",
        "safety_officer_name": "David Okonkwo",
        "safety_officer_decision": "approved",
        "safety_officer_comments": "JSA reviewed and signed. Gas monitor calibrated.",
        "safety_officer_date": "2026-07-24T10:00:00",
        "ap_id": "USR-005",
        "ap_name": "Robert Halliday",
        "ap_decision": "issued",
        "ap_comments": "All isolations verified. Gas test satisfactory.",
        "ap_issue_date": "2026-07-25T05:58:00",
        "closure_requested_by": None,
        "closure_requested_at": None,
        "closure_comments": None,
        "audit_trail": [
            {"timestamp": "2026-07-23T09:00:00", "action": "created", "user": "James Mitchell", "comments": ""},
            {"timestamp": "2026-07-23T09:30:00", "action": "submitted", "user": "James Mitchell", "comments": "Submitted for AA review"},
            {"timestamp": "2026-07-23T14:00:00", "action": "area_authority_approved", "user": "Maria Santos", "comments": "Equipment confirmed isolated"},
            {"timestamp": "2026-07-24T10:00:00", "action": "safety_approved", "user": "David Okonkwo", "comments": "JSA complete"},
            {"timestamp": "2026-07-25T05:58:00", "action": "issued", "user": "Robert Halliday", "comments": "Gas test clear"},
            {"timestamp": "2026-07-25T06:05:00", "action": "activated", "user": "James Mitchell", "comments": "Work commenced"},
        ],
        "created_by": "USR-001",
        "created_at": datetime(2026, 7, 23, 9, 0, ),
        "updated_at": datetime(2026, 7, 25, 6, 5, ),
    },
    {
        "id": "PTW-002",
        "permit_number": "PTW-2026-0002",
        "permit_type": "confined_space",
        "title": "Internal inspection of V-201 atmospheric vessel",
        "scope_of_work": "Confined space entry to inspect internal coating condition, measure wall thickness at 24 sample points using UT, photograph any corrosion.",
        "project_id": "PRJ-001",
        "plant_id": "PLT-001",
        "equipment_ids": ["V-201"],
        "location_description": "CDU Vessel Area, Grid G-09",
        "area_classification": "Non-hazardous (purged)",
        "planned_start": "2026-07-28T07:00:00",
        "planned_end": "2026-07-28T17:00:00",
        "status": "ap_approval",
        "hazards": [
            {"hazard": "Oxygen deficiency inside vessel", "likelihood": "High", "severity": "Critical", "mitigation": "Continuous O2 monitoring, ventilation fan, BA sets on standby"},
            {"hazard": "Residual hydrocarbon vapours", "likelihood": "Medium", "severity": "Critical", "mitigation": "N2 purge followed by air purge; gas test before entry"},
            {"hazard": "Fall from internal ladder", "likelihood": "Medium", "severity": "High", "mitigation": "Harness, lifeline, attendant at top"},
        ],
        "ppe_requirements": [
            {"item": "SCBA / ELSA", "specification": "EN 137 (positive pressure)"},
            {"item": "Full body harness", "specification": "EN 361"},
            {"item": "Intrinsically safe torch", "specification": "ATEX Zone 0"},
        ],
        "isolation_points": [
            {"tag_number": "MV-2011", "description": "V-201 inlet manual valve", "isolation_type": "blind_flange", "verified_by": "USR-004", "verified_at": "2026-07-27T16:00:00"},
            {"tag_number": "MV-2012", "description": "V-201 outlet manual valve", "isolation_type": "blind_flange", "verified_by": "USR-004", "verified_at": "2026-07-27T16:00:00"},
            {"tag_number": "PSV-2001", "description": "V-201 relief valve blinded", "isolation_type": "blind_flange", "verified_by": "USR-005", "verified_at": "2026-07-27T16:30:00"},
        ],
        "gas_tests": [],
        "simops_conflicts": ["Hot work on P-101 nearby — coordinate timing"],
        "emergency_response_ref": "ERP-CSE-001",
        "work_order_id": None,
        "originator_id": "USR-007",
        "originator_name": "Tom Fletcher",
        "originator_date": "2026-07-20T10:00:00",
        "area_authority_id": "USR-004",
        "area_authority_name": "Maria Santos",
        "area_authority_decision": "approved",
        "area_authority_comments": "Vessel deenergised, inerted and depressured",
        "area_authority_date": "2026-07-24T14:00:00",
        "safety_officer_id": "USR-003",
        "safety_officer_name": "David Okonkwo",
        "safety_officer_decision": "approved",
        "safety_officer_comments": "CSE rescue team confirmed available. Rescue plan approved.",
        "safety_officer_date": "2026-07-26T09:00:00",
        "ap_id": "USR-005",
        "ap_name": "Robert Halliday",
        "ap_decision": None,
        "ap_comments": None,
        "ap_issue_date": None,
        "closure_requested_by": None,
        "closure_requested_at": None,
        "closure_comments": None,
        "audit_trail": [
            {"timestamp": "2026-07-20T10:00:00", "action": "created", "user": "Tom Fletcher", "comments": ""},
            {"timestamp": "2026-07-21T08:00:00", "action": "submitted", "user": "Tom Fletcher", "comments": ""},
            {"timestamp": "2026-07-24T14:00:00", "action": "area_authority_approved", "user": "Maria Santos", "comments": ""},
            {"timestamp": "2026-07-26T09:00:00", "action": "safety_approved", "user": "David Okonkwo", "comments": ""},
        ],
        "created_by": "USR-007",
        "created_at": datetime(2026, 7, 20, 10, 0, ),
        "updated_at": datetime(2026, 7, 26, 9, 0, ),
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Safety Procedures
# ─────────────────────────────────────────────────────────────────────────────
PROCEDURES = [
    {
        "id": "PROC-001",
        "code": "SOP-PUMP-001",
        "title": "Centrifugal Pump Startup and Shutdown Procedure",
        "version": "3.2",
        "doc_type": "SOP",
        "category": "Mechanical",
        "project_id": "PRJ-001",
        "plant_id": "PLT-001",
        "equipment_ids": ["P-101", "P-102"],
        "steps": [
            {"step_number": 1, "title": "Pre-startup checks", "description": "Verify all isolation valves open, priming complete, mechanical seal flushed, bearing lube oil level adequate.", "hazards": ["Seal leak", "Dry run"], "controls": ["Visual inspection", "Check oil sight glass"], "responsible_role": "technician"},
            {"step_number": 2, "title": "Motor electrical check", "description": "Confirm motor is energised, check direction of rotation (bump test if first-start).", "hazards": ["Reverse rotation damage"], "controls": ["Phase rotation check at MCC"], "responsible_role": "technician"},
            {"step_number": 3, "title": "Throttle suction valve open, discharge closed", "description": "Open suction valve fully. Keep discharge valve closed/minimum flow to prevent runout.", "hazards": ["Runout condition"], "controls": ["Confirm minimum flow line open"], "responsible_role": "technician"},
            {"step_number": 4, "title": "Start motor", "description": "Initiate start from DCS or local control panel. Confirm motor current draw within limits.", "hazards": ["Overload trip"], "controls": ["Monitor ammeter"], "responsible_role": "technician"},
            {"step_number": 5, "title": "Open discharge valve slowly", "description": "Gradually open discharge valve over 30 seconds. Monitor vibration, temperature, and seal leak-off.", "hazards": ["Water hammer", "Vibration"], "controls": ["Open <5% per 5 seconds"], "responsible_role": "technician"},
            {"step_number": 6, "title": "Confirm normal operation", "description": "Verify flow, differential pressure, vibration, and temperature readings within normal band.", "hazards": [], "controls": ["Check against pump data sheet"], "responsible_role": "technician"},
            {"step_number": 7, "title": "Shutdown sequence", "description": "Close discharge valve, stop motor, close suction valve, depressurise as required.", "hazards": ["Check-valve slam"], "controls": ["Close valve before stopping"], "responsible_role": "technician"},
        ],
        "hazard_register": [
            {"hazard": "Seal failure / hydrocarbon release", "risk_before": "High", "risk_after": "Low", "control_measure": "Double mechanical seal with API Plan 52 buffer fluid"},
            {"hazard": "Bearing failure", "risk_before": "Medium", "risk_after": "Low", "control_measure": "Monthly vibration monitoring, 6-monthly oil analysis"},
        ],
        "ppe_requirements": ["Chemical splash goggles", "Nitrile gloves", "Safety boots", "FR coverall"],
        "tools_required": ["Digital vibration meter", "Infrared thermometer", "Calibrated pressure gauge"],
        "references": ["API 610 Centrifugal Pumps", "Manufacturer OEM Manual Rev.5", "P&ID-CDU-001 Rev.3"],
        "tags": ["pump", "startup", "rotating"],
        "risk_level": "Medium",
        "status": "active",
        "author_id": "USR-001",
        "author_name": "James Mitchell",
        "authored_date": "2024-01-15",
        "peer_reviewer_id": "USR-002",
        "peer_reviewer_name": "Sarah Chen",
        "peer_review_decision": "approved",
        "peer_review_comments": "Step 5 clarified with valve opening rate",
        "peer_review_date": "2024-02-01",
        "tech_reviewer_id": "USR-005",
        "tech_reviewer_name": "Robert Halliday",
        "tech_review_decision": "approved",
        "tech_review_comments": "Aligned with API 610. NPSH note added.",
        "tech_review_date": "2024-02-15",
        "approver_id": "USR-003",
        "approver_name": "David Okonkwo",
        "approver_decision": "approved",
        "approver_comments": "Approved. Effective immediately. Review in 2026.",
        "approval_date": "2024-03-01",
        "effective_date": "2024-03-01",
        "review_due_date": "2026-03-01",
        "audit_trail": [
            {"timestamp": "2024-01-15", "action": "created", "user": "James Mitchell", "comments": ""},
            {"timestamp": "2024-02-01", "action": "peer_review_passed", "user": "Sarah Chen", "comments": ""},
            {"timestamp": "2024-02-15", "action": "technical_review_passed", "user": "Robert Halliday", "comments": ""},
            {"timestamp": "2024-03-01", "action": "approved_activated", "user": "David Okonkwo", "comments": ""},
        ],
        "created_at": datetime(2024, 1, 15, ),
        "updated_at": datetime(2024, 3, 1, ),
    },
    {
        "id": "PROC-002",
        "code": "JSA-HW-001",
        "title": "Job Safety Analysis — Hot Work in Hydrocarbon Areas",
        "version": "2.0",
        "doc_type": "JSA",
        "category": "Safety",
        "project_id": "PRJ-001",
        "plant_id": None,
        "equipment_ids": [],
        "steps": [
            {"step_number": 1, "title": "Identify ignition sources", "description": "Confirm all ignition sources within 15m radius controlled or eliminated.", "hazards": ["Flash fire", "Explosion"], "controls": ["Hot work area demarcation", "Fire watch stationed"], "responsible_role": "safety_officer"},
            {"step_number": 2, "title": "Gas test", "description": "Measure LEL at work point and 3m radius. Must be <10% LEL to proceed.", "hazards": ["Explosive atmosphere"], "controls": ["Calibrated CGI meter", "Document results"], "responsible_role": "safety_officer"},
            {"step_number": 3, "title": "Establish fire watch", "description": "Assign fire watch — person with no other duties, equipped with CO2 extinguisher and alarm access.", "hazards": ["Undetected ignition"], "controls": ["Minimum 1 hour post-work monitoring"], "responsible_role": "supervisor"},
        ],
        "hazard_register": [
            {"hazard": "Flash fire from hydrocarbon vapours", "risk_before": "Critical", "risk_after": "Medium", "control_measure": "Gas testing, barriers, fire watch"},
            {"hazard": "Burns from hot metal", "risk_before": "High", "risk_after": "Low", "control_measure": "FR PPE, hot surface warning signs"},
        ],
        "ppe_requirements": ["FR coverall EN ISO 11612", "Face shield", "Welding gloves EN 12477", "Safety boots S3"],
        "tools_required": ["Calibrated CGI/H2S gas meter", "CO2 extinguisher ≥6kg", "Hot work barriers"],
        "references": ["NFPA 51B Hot Work Standard", "Company HSE Standard HSE-004"],
        "tags": ["hot-work", "welding", "JSA"],
        "risk_level": "High",
        "status": "active",
        "author_id": "USR-003",
        "author_name": "David Okonkwo",
        "authored_date": "2025-06-01",
        "peer_reviewer_id": "USR-006",
        "peer_reviewer_name": "Linda Park",
        "peer_review_decision": "approved",
        "peer_review_comments": "Comprehensive",
        "peer_review_date": "2025-06-15",
        "tech_reviewer_id": "USR-005",
        "tech_reviewer_name": "Robert Halliday",
        "tech_review_decision": "approved",
        "tech_review_comments": "Good",
        "tech_review_date": "2025-06-20",
        "approver_id": "USR-006",
        "approver_name": "Linda Park",
        "approver_decision": "approved",
        "approver_comments": "Approved per NFPA 51B",
        "approval_date": "2025-07-01",
        "effective_date": "2025-07-01",
        "review_due_date": "2027-07-01",
        "audit_trail": [
            {"timestamp": "2025-06-01", "action": "created", "user": "David Okonkwo", "comments": ""},
            {"timestamp": "2025-07-01", "action": "approved_activated", "user": "Linda Park", "comments": ""},
        ],
        "created_at": datetime(2025, 6, 1, ),
        "updated_at": datetime(2025, 7, 1, ),
    },
    {
        "id": "PROC-003",
        "code": "SOP-CSE-001",
        "title": "Confined Space Entry — Vessels and Exchanger Shells",
        "version": "1.0",
        "doc_type": "SOP",
        "category": "Safety",
        "project_id": "PRJ-001",
        "plant_id": None,
        "equipment_ids": [],
        "steps": [],
        "hazard_register": [],
        "ppe_requirements": ["SCBA EN 137", "Full body harness EN 361", "Intrinsically safe lamp"],
        "tools_required": ["Multi-gas detector (O2, LEL, H2S, CO)", "Rescue tripod & winch", "Ventilation fan"],
        "references": ["OSHA 29 CFR 1910.146", "Company CSE Standard HSE-008"],
        "tags": ["confined-space", "vessel", "CSE"],
        "risk_level": "Critical",
        "status": "draft",
        "author_id": "USR-003",
        "author_name": "David Okonkwo",
        "authored_date": "2026-07-01",
        "peer_reviewer_id": None,
        "peer_reviewer_name": None,
        "peer_review_decision": None,
        "peer_review_comments": None,
        "peer_review_date": None,
        "tech_reviewer_id": None,
        "tech_reviewer_name": None,
        "tech_review_decision": None,
        "tech_review_comments": None,
        "tech_review_date": None,
        "approver_id": None,
        "approver_name": None,
        "approver_decision": None,
        "approver_comments": None,
        "approval_date": None,
        "effective_date": None,
        "review_due_date": None,
        "audit_trail": [
            {"timestamp": "2026-07-01", "action": "created", "user": "David Okonkwo", "comments": "First draft"},
        ],
        "created_at": datetime(2026, 7, 1, ),
        "updated_at": datetime(2026, 7, 1, ),
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Managed Work Orders
# ─────────────────────────────────────────────────────────────────────────────
MANAGED_WORK_ORDERS = [
    {
        "id": "MWO-001",
        "wo_number": "WO-2026-0001",
        "title": "P-101 Suction Flange Weld Repair",
        "description": "Repair corroded weld on 6-inch suction flange to prevent seal failure. Critical — equipment at risk of unplanned shutdown.",
        "category": "corrective",
        "priority": "critical",
        "status": "in_progress",
        "project_id": "PRJ-001",
        "plant_id": "PLT-001",
        "equipment_ids": ["P-101"],
        "permit_id": "PTW-001",
        "scheduled_start": "2026-07-25T06:00:00",
        "scheduled_end": "2026-07-25T18:00:00",
        "actual_start": "2026-07-25T06:10:00",
        "actual_end": None,
        "estimated_hours": 10.0,
        "actual_hours": None,
        "tasks": [
            {"seq": 1, "title": "Depressurise and drain suction line", "description": "Ensure line is fully depressurised. Verify with local PI.", "trade": "Process", "estimated_hours": 1.0, "status": "completed", "notes": "Drained and confirmed zero pressure at 05:50"},
            {"seq": 2, "title": "LOTO electrical isolation", "description": "Apply LOTO on MCC-A CB-12. Verify zero energy state.", "trade": "Electrical", "estimated_hours": 0.5, "status": "completed", "notes": "LOTO applied by Robert Halliday"},
            {"seq": 3, "title": "Remove and clean weld joint", "description": "Grind corroded material to bright metal. Measure remaining wall thickness.", "trade": "Mechanical", "estimated_hours": 2.0, "status": "in_progress", "notes": ""},
            {"seq": 4, "title": "Perform weld repair", "description": "MIG weld repair per WPS-001. PWP included in hot work permit.", "trade": "Mechanical", "estimated_hours": 4.0, "status": "pending", "notes": ""},
            {"seq": 5, "title": "NDT inspection", "description": "Dye penetrant test and UT wall thickness measurement.", "trade": "Inspection", "estimated_hours": 1.5, "status": "pending", "notes": ""},
            {"seq": 6, "title": "Reinstate and recommission", "description": "Remove isolations, pressurise slowly, check for leaks. Log in plant log.", "trade": "Process", "estimated_hours": 1.0, "status": "pending", "notes": ""},
        ],
        "materials": [
            {"part_number": "ER70S-6-3.2", "description": "MIG wire 3.2mm ER70S-6", "qty_required": 2, "qty_issued": 2, "unit": "kg"},
            {"part_number": "GKT-6IN-300LB", "description": "6-inch 300lb RF spiral wound gasket", "qty_required": 1, "qty_issued": 1, "unit": "ea"},
        ],
        "safety_requirements": ["Hot work permit PTW-2026-0001 required", "LOTO procedure SOP-LOTO-001", "FR PPE mandatory", "Gas monitor to be worn throughout"],
        "created_by_id": "USR-001",
        "created_by_name": "James Mitchell",
        "created_at": datetime(2026, 7, 23, 8, 0, ),
        "approver_id": "USR-002",
        "approver_name": "Sarah Chen",
        "approval_decision": "approved",
        "approval_comments": "Priority justified by leak rate. PTW to be raised concurrently.",
        "approval_date": "2026-07-23T14:30:00",
        "assigned_to": [{"id": "USR-001", "name": "James Mitchell", "role": "Lead Welder"}],
        "started_by_id": "USR-001",
        "started_by_name": "James Mitchell",
        "started_at": "2026-07-25T06:10:00",
        "completed_by_id": None,
        "completed_by_name": None,
        "completed_at": None,
        "completion_notes": None,
        "verified_by_id": None,
        "verified_by_name": None,
        "verification_decision": None,
        "verification_comments": None,
        "verified_at": None,
        "audit_trail": [
            {"timestamp": "2026-07-23T08:00:00", "action": "created", "user": "James Mitchell", "comments": "Raised following DCS vibration alarm"},
            {"timestamp": "2026-07-23T08:30:00", "action": "submitted", "user": "James Mitchell", "comments": ""},
            {"timestamp": "2026-07-23T14:30:00", "action": "approved", "user": "Sarah Chen", "comments": "Priority confirmed"},
            {"timestamp": "2026-07-24T09:00:00", "action": "scheduled", "user": "Sarah Chen", "comments": "Scheduled for 25 July"},
            {"timestamp": "2026-07-25T06:10:00", "action": "started", "user": "James Mitchell", "comments": "Work commenced"},
        ],
        "updated_at": datetime(2026, 7, 25, 6, 10, ),
    },
    {
        "id": "MWO-002",
        "wo_number": "WO-2026-0002",
        "title": "HE-301 Tube Bundle Replacement",
        "description": "Scheduled replacement of tube bundle in HE-301. Original bundle is at 40% efficiency. Replacement bundle pre-ordered and in stores.",
        "category": "preventive",
        "priority": "high",
        "status": "draft",
        "project_id": "PRJ-001",
        "plant_id": "PLT-001",
        "equipment_ids": ["HE-301"],
        "permit_id": None,
        "scheduled_start": "2026-09-15T06:00:00",
        "scheduled_end": "2026-09-17T18:00:00",
        "actual_start": None,
        "actual_end": None,
        "estimated_hours": 36.0,
        "actual_hours": None,
        "tasks": [
            {"seq": 1, "title": "Isolate and drain heat exchanger", "description": "", "trade": "Process", "estimated_hours": 2.0, "status": "pending", "notes": ""},
            {"seq": 2, "title": "Remove channel covers and old tube bundle", "description": "", "trade": "Mechanical", "estimated_hours": 8.0, "status": "pending", "notes": ""},
            {"seq": 3, "title": "Clean shell side and inspect", "description": "", "trade": "Mechanical", "estimated_hours": 4.0, "status": "pending", "notes": ""},
            {"seq": 4, "title": "Install new tube bundle", "description": "", "trade": "Mechanical", "estimated_hours": 10.0, "status": "pending", "notes": ""},
            {"seq": 5, "title": "Hydraulic pressure test", "description": "Hydro test to 1.5× design pressure", "trade": "Inspection", "estimated_hours": 4.0, "status": "pending", "notes": ""},
            {"seq": 6, "title": "Reinstate and performance check", "description": "", "trade": "Process", "estimated_hours": 3.0, "status": "pending", "notes": ""},
        ],
        "materials": [
            {"part_number": "TB-HE301-STD", "description": "HE-301 replacement tube bundle (SS 316L)", "qty_required": 1, "qty_issued": 0, "unit": "ea"},
        ],
        "safety_requirements": ["Cold work permit required", "PTW for confined space entry (shell side)"],
        "created_by_id": "USR-002",
        "created_by_name": "Sarah Chen",
        "created_at": datetime(2026, 7, 15, ),
        "approver_id": None,
        "approver_name": None,
        "approval_decision": None,
        "approval_comments": None,
        "approval_date": None,
        "assigned_to": [],
        "started_by_id": None,
        "started_by_name": None,
        "started_at": None,
        "completed_by_id": None,
        "completed_by_name": None,
        "completed_at": None,
        "completion_notes": None,
        "verified_by_id": None,
        "verified_by_name": None,
        "verification_decision": None,
        "verification_comments": None,
        "verified_at": None,
        "audit_trail": [
            {"timestamp": "2026-07-15T10:00:00", "action": "created", "user": "Sarah Chen", "comments": "Scheduled per PMQ-2026 maintenance plan"},
        ],
        "updated_at": datetime(2026, 7, 15, ),
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Incident Reports
# ─────────────────────────────────────────────────────────────────────────────
INCIDENT_REPORTS = [
    {
        "id": "INC-001",
        "incident_number": "INC-2026-0001",
        "title": "Hydrocarbon vapour release from P-101 seal — near miss",
        "description": "Operator noticed small vapour cloud around P-101 mechanical seal area during routine round. Pump was immediately shutdown. No ignition occurred.",
        "incident_type": "near_miss",
        "severity": "P3",
        "status": "capa",
        "project_id": "PRJ-001",
        "plant_id": "PLT-001",
        "equipment_ids": ["P-101"],
        "location_description": "CDU Pump Bay A",
        "occurred_at": "2026-07-22T14:30:00",
        "reported_at": "2026-07-22T14:45:00",
        "reported_by_id": "USR-001",
        "reported_by_name": "James Mitchell",
        "persons_involved": [],
        "witnesses": [
            {"name": "Sarah Chen", "statement": "Confirmed vapour cloud visible from 10m away. Activated manual alarm."},
        ],
        "immediate_actions": [
            "Manual pump shutdown activated",
            "Area evacuated",
            "Fire alarm raised",
            "Emergency team notified",
            "Area ventilated and gas tested",
        ],
        "investigation_lead_id": "USR-003",
        "investigation_lead_name": "David Okonkwo",
        "investigation_team": [
            {"id": "USR-002", "name": "Sarah Chen", "role": "Supervisor"},
            {"id": "USR-005", "name": "Robert Halliday", "role": "Engineering"},
        ],
        "root_causes": [
            {"level": "1", "cause": "Mechanical seal faces worn beyond tolerance", "category": "Equipment Failure"},
            {"level": "2", "cause": "Seal replacement overdue by 45 days", "category": "Maintenance Planning"},
            {"level": "3", "cause": "Predictive maintenance alerts not escalated", "category": "Management System"},
        ],
        "contributing_factors": [
            "Vibration alarm ignored on DCS for 3 days",
            "Temporary operator assigned — unfamiliar with pump history",
            "Maintenance backlog due to staffing",
        ],
        "timeline": [
            {"time": "2026-07-22T14:30:00", "event": "Vapour cloud detected", "description": "Operator James Mitchell observed vapour during routine round"},
            {"time": "2026-07-22T14:32:00", "event": "Pump shutdown", "description": "Manual shutdown activated from local panel"},
            {"time": "2026-07-22T14:35:00", "event": "Area evacuated", "description": "All personnel cleared from pump bay"},
            {"time": "2026-07-22T14:45:00", "event": "Incident reported", "description": "Formal report submitted to HSE"},
        ],
        "capa_items": [
            {"id": "CAPA-001", "action_type": "corrective", "description": "Replace P-101 mechanical seal immediately", "assigned_to_id": "USR-001", "assigned_to_name": "James Mitchell", "due_date": "2026-07-25", "status": "completed", "completed_at": "2026-07-25T18:00:00", "completed_by_name": "James Mitchell", "evidence": "WO-2026-0001 completed. New seal installed and leak tested."},
            {"id": "CAPA-002", "action_type": "preventive", "description": "Review and update predictive maintenance alert escalation procedure", "assigned_to_id": "USR-002", "assigned_to_name": "Sarah Chen", "due_date": "2026-08-15", "status": "open"},
            {"id": "CAPA-003", "action_type": "preventive", "description": "Implement mandatory handover checklist for temporary operators on critical equipment", "assigned_to_id": "USR-003", "assigned_to_name": "David Okonkwo", "due_date": "2026-08-31", "status": "open"},
        ],
        "reviewed_by_id": "USR-006",
        "reviewed_by_name": "Linda Park",
        "review_comments": "Investigation thorough. Root causes well identified. Ensure CAPA-002 and 003 are completed on time.",
        "reviewed_at": "2026-07-24T11:00:00",
        "closed_by_id": None,
        "closed_by_name": None,
        "closed_at": None,
        "closure_comments": None,
        "audit_trail": [
            {"timestamp": "2026-07-22T14:45:00", "action": "reported", "user": "James Mitchell", "comments": ""},
            {"timestamp": "2026-07-23T09:00:00", "action": "investigation_assigned", "user": "David Okonkwo", "comments": ""},
            {"timestamp": "2026-07-24T09:00:00", "action": "root_cause_recorded", "user": "David Okonkwo", "comments": "3 root causes identified"},
            {"timestamp": "2026-07-24T10:00:00", "action": "capa_added", "user": "system", "comments": "corrective: Replace P-101 mechanical seal immedia"},
            {"timestamp": "2026-07-24T11:00:00", "action": "management_reviewed", "user": "Linda Park", "comments": ""},
        ],
        "created_at": datetime(2026, 7, 22, 14, 45, ),
        "updated_at": datetime(2026, 7, 24, 11, 0, ),
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Quality Inspections
# ─────────────────────────────────────────────────────────────────────────────
QUALITY_INSPECTIONS = [
    {
        "id": "QI-001",
        "inspection_number": "QI-2026-0001",
        "title": "P-101 Post-Repair Quality Inspection",
        "inspection_type": "equipment",
        "project_id": "PRJ-001",
        "plant_id": "PLT-001",
        "equipment_ids": ["P-101"],
        "status": "scheduled",
        "priority": "high",
        "scheduled_date": "2026-07-26",
        "actual_date": None,
        "inspector_id": "USR-007",
        "inspector_name": "Tom Fletcher",
        "checklist_items": [
            {"seq": 1, "category": "Visual", "check_item": "Weld appearance — no visible cracks, porosity, or undercutting", "criteria": "Meets AWS D1.1 visual inspection criteria", "result": None, "findings": "", "evidence_ref": ""},
            {"seq": 2, "category": "NDT", "check_item": "Dye penetrant test on weld", "criteria": "No indications per ASME V Art. 6", "result": None, "findings": "", "evidence_ref": ""},
            {"seq": 3, "category": "Dimensional", "check_item": "Wall thickness measurement ≥ minimum design wall", "criteria": "WT ≥ 8.74mm per API 574", "result": None, "findings": "", "evidence_ref": ""},
            {"seq": 4, "category": "Mechanical", "check_item": "Flange alignment and bolt load check", "criteria": "Angular misalignment < 0.5°, all bolts torqued to specification", "result": None, "findings": "", "evidence_ref": ""},
            {"seq": 5, "category": "Leak test", "check_item": "Pressure test to 1.1× MAWP", "criteria": "No visible leaks for 30 minutes", "result": None, "findings": "", "evidence_ref": ""},
        ],
        "non_conformances": [],
        "observations": [],
        "overall_score": None,
        "summary_notes": None,
        "reviewer_id": "USR-005",
        "reviewer_name": "Robert Halliday",
        "reviewer_decision": None,
        "reviewer_comments": None,
        "reviewed_at": None,
        "audit_trail": [
            {"timestamp": "2026-07-23T15:00:00", "action": "created", "user": "Tom Fletcher", "comments": "Created following WO-2026-0001 repair"},
        ],
        "created_by": "USR-007",
        "created_at": datetime(2026, 7, 23, 15, 0, ),
        "updated_at": datetime(2026, 7, 23, 15, 0, ),
    },
    {
        "id": "QI-002",
        "inspection_number": "QI-2026-0002",
        "title": "CDU Monthly Safety Walk — July 2026",
        "inspection_type": "safety_audit",
        "project_id": "PRJ-001",
        "plant_id": "PLT-001",
        "equipment_ids": [],
        "status": "closed_with_findings",
        "priority": "medium",
        "scheduled_date": "2026-07-15",
        "actual_date": "2026-07-15",
        "inspector_id": "USR-003",
        "inspector_name": "David Okonkwo",
        "checklist_items": [
            {"seq": 1, "category": "Housekeeping", "check_item": "No oil/water puddles on walkways", "criteria": "Dry and clean", "result": "fail", "findings": "Oil puddle near P-101 base plate approx 0.5m²", "evidence_ref": "Photo-QI002-01"},
            {"seq": 2, "category": "Fire safety", "check_item": "Fire extinguishers charged and in date", "criteria": "Green indicator, inspection tag current", "result": "pass", "findings": "", "evidence_ref": ""},
            {"seq": 3, "category": "PPE", "check_item": "All personnel wearing correct PPE", "criteria": "FR coverall, safety glasses, helmet, boots", "result": "pass", "findings": "", "evidence_ref": ""},
            {"seq": 4, "category": "Signage", "check_item": "Hazard warning signs legible and in place", "criteria": "No missing or faded signs", "result": "pass", "findings": "", "evidence_ref": ""},
            {"seq": 5, "category": "Emergency", "check_item": "Escape routes clear and unobstructed", "criteria": "3m minimum clear width", "result": "fail", "findings": "Scaffolding material stored at emergency exit A — reduces width to 1.2m", "evidence_ref": "Photo-QI002-02"},
        ],
        "non_conformances": [
            {"id": "NC-001", "description": "Oil puddle on walkway near P-101 — slip hazard", "severity": "major", "action_required": "Clean up and investigate source. Repair any leak.", "due_date": "2026-07-16", "status": "closed"},
            {"id": "NC-002", "description": "Scaffolding blocking emergency exit A", "severity": "critical", "action_required": "Immediately relocate scaffolding material to designated laydown area", "due_date": "2026-07-15", "status": "closed"},
        ],
        "observations": ["Good engagement from operators — all able to explain emergency muster point"],
        "overall_score": 60.0,
        "summary_notes": "2 NCs raised. Both were closed by end of shift. Root cause for oil puddle attributed to P-101 seal degradation — now addressed via WO-2026-0001.",
        "reviewer_id": "USR-006",
        "reviewer_name": "Linda Park",
        "reviewer_decision": "closed_with_findings",
        "reviewer_comments": "NCs closed satisfactorily. Recommend P-101 seal inspection to prevent recurrence.",
        "reviewed_at": "2026-07-16T09:00:00",
        "audit_trail": [
            {"timestamp": "2026-07-10T10:00:00", "action": "created", "user": "David Okonkwo", "comments": "Monthly scheduled safety walk"},
            {"timestamp": "2026-07-15T08:00:00", "action": "started", "user": "David Okonkwo", "comments": ""},
            {"timestamp": "2026-07-15T11:00:00", "action": "submitted_for_review", "user": "David Okonkwo", "comments": "2 NCs raised"},
            {"timestamp": "2026-07-16T09:00:00", "action": "closed_with_findings", "user": "Linda Park", "comments": "NCs verified closed"},
        ],
        "created_by": "USR-003",
        "created_at": datetime(2026, 7, 10, ),
        "updated_at": datetime(2026, 7, 16, 9, 0, ),
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Action Items
# ─────────────────────────────────────────────────────────────────────────────
ACTION_ITEMS = [
    {
        "id": "ACT-001",
        "action_number": "ACT-2026-0001",
        "title": "Update PM alert escalation procedure",
        "description": "Review DCS alarm management and ensure critical vibration/seal alerts auto-escalate to supervisor after 8 hours with no acknowledgement.",
        "source_type": "incident",
        "source_id": "INC-001",
        "source_ref": "INC-2026-0001 CAPA-002",
        "action_type": "preventive",
        "priority": "high",
        "status": "in_progress",
        "project_id": "PRJ-001",
        "plant_id": "PLT-001",
        "assigned_to_id": "USR-002",
        "assigned_to_name": "Sarah Chen",
        "due_date": "2026-08-15",
        "completed_by_id": None,
        "completed_by_name": None,
        "completed_at": None,
        "completion_evidence": None,
        "verifier_id": "USR-003",
        "verifier_name": "David Okonkwo",
        "verification_comments": None,
        "verified_at": None,
        "created_by": "USR-003",
        "created_at": datetime(2026, 7, 24, ),
        "updated_at": datetime(2026, 7, 24, ),
    },
    {
        "id": "ACT-002",
        "action_number": "ACT-2026-0002",
        "title": "Temporary operator handover checklist",
        "description": "Develop and implement mandatory handover checklist for temporary/relief operators assigned to critical rotating equipment.",
        "source_type": "incident",
        "source_id": "INC-001",
        "source_ref": "INC-2026-0001 CAPA-003",
        "action_type": "preventive",
        "priority": "medium",
        "status": "open",
        "project_id": "PRJ-001",
        "plant_id": None,
        "assigned_to_id": "USR-003",
        "assigned_to_name": "David Okonkwo",
        "due_date": "2026-08-31",
        "completed_by_id": None,
        "completed_by_name": None,
        "completed_at": None,
        "completion_evidence": None,
        "verifier_id": None,
        "verifier_name": None,
        "verification_comments": None,
        "verified_at": None,
        "created_by": "USR-003",
        "created_at": datetime(2026, 7, 24, ),
        "updated_at": datetime(2026, 7, 24, ),
    },
]
